In [79]:
import pandas as pd 
import seaborn as sns

In [80]:
data= sns.load_dataset("titanic")

In [81]:
data.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [82]:
data.shape

(891, 15)

In [83]:
data.duplicated().sum()

np.int64(107)

In [90]:
data=data.drop_duplicates()

In [93]:
data.shape

(349, 5)

In [29]:
data=data.drop(['who'	,'adult_male',	'deck'],axis=1)

In [31]:
data.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,Cherbourg,yes,False

In [40]:
# non-destructive (returns a new DataFrame)
#data = data.drop(data.index[3:7])
# to reindex rows after dropping, uncomment:
data = data.drop(data.index[3:7]).reset_index(drop=True)
#data = data.drop(data.index[3:7], axis=0)

# or in-place
# data.drop(index=range(3,7), inplace=True)

In [41]:
data.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
4,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
6,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
7,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
8,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
9,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True

In [72]:
from sklearn.model_selection import  train_test_split

In [85]:
data = data.drop(['sibsp','parch','fare','embarked','class','who','adult_male','deck','embark_town','alone'], axis=1, errors='ignore')

In [86]:
data.head()

   survived  pclass     sex   age alive
0         0       3    male  22.0    no
1         1       1  female  38.0   yes
2         1       3  female  26.0   yes
3         1       1  female  35.0   yes
4         0       3    male  35.0    no

In [87]:
x=data.iloc[:,1:]

y=data.iloc[:,:1]

In [88]:
x

     pclass     sex   age alive
0         3    male  22.0    no
1         1  female  38.0   yes
2         3  female  26.0   yes
3         1  female  35.0   yes
4         3    male  35.0    no
..      ...     ...   ...   ...
886       2    male  27.0    no
887       1  female  19.0   yes
888       3  female   NaN    no
889       1    male  26.0   yes
890       3    male  32.0    no

[891 rows x 4 columns]

In [89]:
y

     survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(
    x,
    y,
    test_size=0.20,
    random_state=42
    
)

In [58]:
xtrain

     pclass     sex   age alive
603       3    male   NaN    no
433       3    male  20.0    no
360       3  female   NaN   yes
355       3    male  35.0    no
81        3    male  24.0    no
..      ...     ...   ...   ...
106       3  female  17.0    no
270       3    male   7.0    no
860       3    male   NaN    no
435       2  female  28.0   yes
102       1    male  47.0    no

[706 rows x 4 columns]

In [59]:
xtest

     pclass     sex   age alive
44        1  female  49.0   yes
806       3    male  30.5    no
720       2    male  25.0    no
660       3    male  43.0    no
878       2    male  27.0    no
..      ...     ...   ...   ...
118       3    male   NaN    no
388       3  female  31.0    no
494       3  female   NaN    no
29        3    male  21.0    no
247       3  female  29.0   yes

[177 rows x 4 columns]

In [60]:
ytrain

     survived
603         0
433         0
360         1
355         0
81          0
..        ...
106         0
270         0
860         0
435         1
102         0

[706 rows x 1 columns]

In [61]:
ytest

     survived
44          1
806         0
720         0
660         0
878         0
..        ...
118         0
388         0
494         0
29          0
247         1

[177 rows x 1 columns]