In [7]:
import pandas as pd
import requests

In [8]:

# 1. Define a real, live URL (Coordinates for New York City)
url = "https://api.open-meteo.com/v1/forecast"
params = {
    "latitude": 40.7128,
    "longitude": -74.0060,
    "hourly": "temperature_2m,relative_humidity_2m,wind_speed_10m",
    "forecast_days": 3,
}

In [9]:
print("Fetching real-time data from Open-Meteo...")
response = requests.get(url, params=params)

Fetching real-time data from Open-Meteo...

In [10]:
print("\n--- 1. Raw JSON Keys ---")
print(raw_json.keys())

--- 1. Raw JSON Keys ---
dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'hourly_units', 'hourly'])

In [11]:
print("\n--- 2. Inside the 'hourly' key (The nested data) ---")
print(raw_json["hourly"].keys())

--- 2. Inside the 'hourly' key (The nested data) ---
dict_keys(['time', 'temperature_2m', 'relative_humidity_2m', 'wind_speed_10m'])

In [12]:

    # 3. Load the nested 'hourly' dictionary directly into a Pandas DataFrame
df_raw = pd.DataFrame(raw_json["hourly"])

print("\n--- 3. Raw Data Transformed to DataFrame ---")
display(df_raw.head(10))

--- 3. Raw Data Transformed to DataFrame ---

               time  temperature_2m  relative_humidity_2m  wind_speed_10m
0  2026-06-14T00:00            28.8                    36             7.9
1  2026-06-14T01:00            27.1                    37             5.9
2  2026-06-14T02:00            26.0                    41             1.6
3  2026-06-14T03:00            24.1                    49             0.8
4  2026-06-14T04:00            24.2                    48             3.3
5  2026-06-14T05:00            23.3                    51             5.4
6  2026-06-14T06:00            23.1                    54             4.4
7  2026-06-14T07:00            22.4                    61             9.0
8  2026-06-14T08:00            21.5                    65             6.7
9  2026-06-14T09:00            21.4                    64             3.6

In [13]:
print("\n--- 4. Data Info (Types & Shapes) ---")
display(df_raw.info())

--- 4. Data Info (Types & Shapes) ---
<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  72 non-null     str
 1   temperature_2m        72 non-null     float64
 2   relative_humidity_2m  72 non-null     int64
 3   wind_speed_10m        72 non-null     float64
dtypes: float64(2), int64(1), str(1)
memory usage: 3.5 KB

None

In [14]:

if response.status_code == 200:
    # 2. Extract the raw JSON
    raw_json = response.json()

    print("\n--- 1. Raw JSON Keys ---")
    print(raw_json.keys())

    print("\n--- 2. Inside the 'hourly' key (The nested data) ---")
    print(raw_json["hourly"].keys())

    # 3. Load the nested 'hourly' dictionary directly into a Pandas DataFrame
    df_raw = pd.DataFrame(raw_json["hourly"])

    print("\n--- 3. Raw Data Transformed to DataFrame ---")
    display(df_raw.head(10))

    print("\n--- 4. Data Info (Types & Shapes) ---")
    display(df_raw.info())

else:
    print(f"Failed to fetch data. Status code: {response.status_code}")

--- 1. Raw JSON Keys ---
dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'hourly_units', 'hourly'])

--- 2. Inside the 'hourly' key (The nested data) ---
dict_keys(['time', 'temperature_2m', 'relative_humidity_2m', 'wind_speed_10m'])

--- 3. Raw Data Transformed to DataFrame ---

               time  temperature_2m  relative_humidity_2m  wind_speed_10m
0  2026-06-14T00:00            28.8                    36             7.9
1  2026-06-14T01:00            27.1                    37             5.9
2  2026-06-14T02:00            26.0                    41             1.6
3  2026-06-14T03:00            24.1                    49             0.8
4  2026-06-14T04:00            24.2                    48             3.3
5  2026-06-14T05:00            23.3                    51             5.4
6  2026-06-14T06:00            23.1                    54             4.4
7  2026-06-14T07:00            22.4                    61             9.0
8  2026-06-14T08:00            21.5                    65             6.7
9  2026-06-14T09:00            21.4                    64             3.6

--- 4. Data Info (Types & Shapes) ---
<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  72 non-null     str
 1   temperature_2m        72 non-null     float64
 2   relative_humidity_2m  72 non-null     int64
 3   wind_speed_10m        72 non-null     float64
dtypes: float64(2), int64(1), str(1)
memory usage: 3.5 KB

None

In [16]:
df_raw.to_csv("forcastdata.csv",index=False)